### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by geek80** [Parijat29/COVID-19-India-R0-Analysis#1]
Hello,

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/LC9NX2

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by Parijat-K** [comment]
Hello,
Thank you for your interest. I will be more than glad to keep the dataset up to date if it helps anyone. Currently, I am trying to set up a GitHub action to refresh the data daily. If there is an API available, I can use that to update the data in CoronaWhy also.

**Comment by geek80** [comment]
Thanks for the reply. Our configuration is setup in that way, that all updates from Github repos are synchronized with Dataverse. You can register in Dataverse and update the metadata.

**Comment by Parijat-K** [comment]
That's great. I have configured GitHub actions to update the data daily in the repo. 
I have also registered in the Dataverse with my email id - khanparijat@gmail.com
I don't have access yet to make any modifications to the dataset. Please let me know the steps to claim ownership of that dataset if any.

**Comment by geek80** [comment]
Thanks we will give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset.

**Comment by geek80** [comment]
We have given you the permissions to edit your Dataset. You can add description and keywords to your dataset. Thanks.

**Comment by Parijat-K** [comment]
Thank you. I have updated all the information I could think of. It is under review. Please let me know if I missed anything.
